apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: services
build:
  artifacts:
    - image: services
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/producer.yaml
    # - k8s/classifier.yaml
