---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wiki.page-create
  namespace: kafka
  labels:
    strimzi.io/cluster: data-bus
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wiki.page-create.filtered
  namespace: kafka
  labels:
    strimzi.io/cluster: data-bus
spec:
  partitions: 1
  replicas: 1
